CHAT_DATA_KEY_SELECTED_CANTEEN = 'user_selected_canteen'
CHAT_DATA_KEY_SELECTED_PRICE_GROUP = 'user_selected_price_group'
CHAT_DATA_PREVIOUSLY_SELECTED_DATE = 'user_selected_previous_date'
BOT_DATA_KEY_PUSH_REGISTER = 'push_notification_uids'
